### ISSUE TITLE
Reverse proxy (e.g., nginx)?

### ISSUE THREAD

**Issue by adamliter** [mvdoc/psiturk-docker#3]
(cc: @deargle)

I wonder if it's worth adding support for a reverse proxy. Doing so is relatively trivial, and I'm happy to open a PR, but  wanted to get feedback first. Specifically, I was wondering how you'd want to do this since it changes the configuration a bit. You have to specify the `adserver_revproxy_host` and `adserver_revproxy_port` options on `config.txt`. So it largely only makes sense to do this if you have a machine with a static IP address and, optionally, a domain name.

Anyway, here's a diff of what you'd need to change:

```diff
diff --git a/default.conf b/default.conf
new file mode 100644
index 0000000..8628cf9
--- /dev/null
+++ b/default.conf
@@ -0,0 +1,13 @@
+server {
+    listen 80 default_server;
+    server_name localhost;
+    root /var/www/psiturk-example;
+
+    location / {
+        try_files $uri @proxy_to_psiturk;
+    }
+
+    location @proxy_to_psiturk {
+        proxy_pass http://psiturk:22362;
+    }
+}
diff --git a/docker-compose.yml b/docker-compose.yml
index e0be122..5ed284d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,5 +1,17 @@
 version: '3'
 services:
+services:
+  nginx:
+    image: nginx:latest
+    restart: always
+    ports:
+      - 80:80
+    volumes:
+      - ./exp/psiturk-example:/var/www/psiturk-example:ro
+      - ./default.conf:/etc/nginx/conf.d/default.conf
+    links:
+      - psiturk
+
   db:
     image: mysql:latest
     volumes:
diff --git a/exp/psiturk-example/config.txt b/exp/psiturk-example/config.txt
index 8397fec..454cfd8 100644
--- a/exp/psiturk-example/config.txt
+++ b/exp/psiturk-example/config.txt
@@ -12,7 +12,7 @@ organization_name = New Great University
 browser_exclude_rule = MSIE, mobile, tablet

 [Database Parameters]
-database_url = mysql://psiturk:psiturk@db:3306/participants
+database_url = mysql://psiturk:psiturk@db:3306/participants
 table_name = turkdemo

 [Server Parameters]
@@ -25,6 +25,8 @@ debug = true
 login_username = examplename
 login_pw = examplepassword
 threads = auto
+adserver_revproxy_host = www.location.of.your.revproxy.sans.protocol.com
+adserver_revproxy_port = 80

 [Task Parameters]
 experiment_code_version = 1.0
```

**Comment by mvdoc** [comment]
Hi @adamliter,
thanks for opening the issue. I'm not super familiar with it, so what exactly would be the advantage of adding a reverse proxy? And would it be of benefit only if you have a static IP and a domain name?

Thanks

**Comment by deargle** [comment]
Gunicorn servers (the psiturk server) are [not meant to ever be public-facing servers](http://docs.gunicorn.org/en/stable/deploy.html). It is atrocious at serving static content. Things can get overloaded very easily. A reverse proxy server such as nginx in front is recommended for handling static content. That's what this part example nginx config does -- 

```
location / {
        try_files $uri @proxy_to_psiturk;
    }
```
attempts to serve the request from the static content, but if that fails, pass the request on to the gunicorn psiturk server. 

> So it largely only makes sense to do this if you have a machine with a static IP address and, optionally, a domain name.

Not necessarily a static ip, but of course you need a public-facing ip. But don't all psiturk experiments rely on having a public ip address? When `hit create` is called, the public ip of the code-calling server is pulled and passed on to the psiturk ad server so that the ad server knows where to forward participants to if they accept the hit. And you don't need a domain name. It's just nice to have. I wrote the `adserver_revproxy_host` example that way just because I'm so used to using heroku or whatever which gives you a domain name for free. `adserver_revproxy_host` can't just assume that it can pull the current IP address though and use that, because places like heroku only work if you use your domain name. Which psiturk can't know. I guess I could make that more clear in the docs, but TBH I don't know of anyone besides myself who uses that functionality :-\

EDIT: And I'm not well-versed in what this additional nginx config does, but [the docs](http://docs.gunicorn.org/en/stable/deploy.html) recommend `proxy-set-header`, too:

```
location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # enable this if and only if you use HTTPS
      # proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Host $http_host;
      # we don't want nginx trying to do something clever with
      # redirects, we set the Host: header above already.
      proxy_redirect off;
      proxy_pass http://app_server;
    }
```

EDIT 2: In an ideal world, all psiturk instances would be behind a rev proxy. But setting one up is more than what many psiturk users can handle, unless of course their experiments won't run properly because they have too many images or whatever, then they're required to set up something. A Docker deploy is an ideal setting for giving a rev proxy to everyone.

**Comment by adamliter** [comment]
@mvdoc: I think @deargle covered the reasons well. Basically, nginx does a better job of handling traffic and an especially better job of serving static content. So if you have (lots of) images, sound files, *etc.* in your experiment, this will work a lot better, especially when multiple people are doing the experiment at the same time.

Regarding:

> So it largely only makes sense to do this if you have a machine with a static IP address and, optionally, a domain name.

What I meant by this was that I'm not sure that this would work all that well if you tried to use the (experimental?) psiTurk feature of running an experiment on a computer behind a wifi router, for example. I've never looked into how psiTurk implemented that feature, so I'm not sure, but I suspect it could run into problems. Maybe @deargle knows whether this would work?

@deargle's clarifications are good points, though. If this is being run on a server that serves multiple things, you'd need the correct domain name in order for the server to know which application to pass the traffic to; you would not want to use the IP address.

But anyway, I think @deargle is right that this would basically be usable by anyone running a psiTurk experiment (except perhaps anyone running the experiment behind a router?).

And yes, as @deargle points out, it's probably worth at least setting the `X-Forwarded-For` header.

Setting `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` appends the IP address of the client machine to the `X-Forwarded-For` header as it gets passed along to the application behind the reverse proxy (`proxy_set_header X-Forwarded-For $remote_addr;` sets it to the IP address of the client machine, rather than appending it).

You'd want to set the `Host` header if your application that nginx is passing the traffic to cares about the hostname; otherwise `proxy_pass` will set the `Host` header to the hostname of the machine that is running nginx.

**Comment by deargle** [comment]
> What I meant by this was that I'm not sure that this would work all that
well if you tried to use the (experimental?) psiTurk feature of running an
experiment on a computer behind a wifi router, for example. I've never
looked into how psiTurk implemented that feature, so I'm not sure, but I
suspect it could run into problems. Maybe @deargle
<https://github.com/deargle> knows whether this would work?

What I've heard is that that tunneling feature is dead, without plans to
fix it, because implementer left the NYU lab that developed and maintains
the servers etc for psiturk.

**Comment by adamliter** [comment]
Thanks @deargle. So @mvdoc, I think that means basically anyone would be able to use this (assuming they're not using the dead tunneling feature). Something would just need to be added to the README, I think, in order to point out that you need to specify either your machine's IP address or a domain name that resolves to your machine's IP address in `config.txt`'s `adserver_revproxy_host` option and that you need to specify port 80 for `config.txt`'s `adserver_revproxy_port` option.

Let me know your thoughts. I'm happy to open a pull request, but I also understand if you'd rather not add this since it adds a little bit of complexity to the setup. Granted, I do think it's worth the added complexity for the reasons that @deargle quoted from the Gunicorn docs.

**Comment by mvdoc** [comment]
Yep, it does make a lot of sense. Thanks for the explanation! Please feel
free to send a PR with whatever you think the best configs are. Thanks!

**Comment by adamliter** [comment]
@mvdoc 🎉 #4 

Dunno if @deargle wants to weigh in on the PR before it gets merged.
