### ISSUE TITLE
Add image to dockerhub

### ISSUE THREAD

**Issue by twiecki** [mvdoc/psiturk-docker#6]
Is it possible to publish this to dockerhub to make deployment easier? Or is that not supported because of docker-compose?

**Comment by mvdoc** [comment]
I think I can push the psiturk image to dockerhub, so it doesn't need to be
built every time. I'll put it on my list and try this asap.

**Comment by mvdoc** [comment]
Actually I forgot that the psiturk images are already on dockerhub. It
should be sufficient to run docker-compose up and then it will pull all
images.

Did you encounter any particular issue?

**Comment by twiecki** [comment]
Great! I just tried it and it worked like a charm. Really useful to have the nginx setup as well in here.

**Comment by twiecki** [comment]
I want to try deploying this on openshift next. Do you have any experience with this? Or suggestions for alternatives you already tried successfully?

**Comment by mvdoc** [comment]
Alright, I pushed the docker image to docker hub. Note that it's always using the latest version of psiturk. If you need a specific version, you can use these docker images (and modify the `docker-compose.yml`): https://hub.docker.com/r/adamliter/psiturk/

Re openshift: no, I'm sorry, I never used it. I personally used this configuration on a personal server. However I would be very interested to know how easy it is to put this on openshift. I have a feeling that one needs to use kubernetes instead of docker compose, but apparently there's an easy way to convert docker-compose to kubernetes (https://kubernetes.io/docs/tools/kompose/user-guide/#openshift).

So if you have time, it'd be great if you could share how it worked for you.

**Comment by twiecki** [comment]
Great, thanks!

I'll report back if I get openshift to work. I gave it a shot but now trying it on ec2 to get going.

**Comment by adamliter** [comment]
FWIW, I've been deploying my stuff on Linode, and they have pretty cheap server plans.
